/**
 * withAsyncStorageSize — raise Android AsyncStorage's SQLite cap from 6 MB.
 *
 * @react-native-async-storage defaults to a 6 MB database on Android. Every run
 * (full track as JSON) lives there, so after roughly 15 h of total recording
 * saveRun started throwing SQLITE_FULL and new runs could not be stored. The
 * library reads `AsyncStorage_db_size_in_MB` from gradle.properties; android/ is
 * regenerated by `expo prebuild`, so set it here to survive every prebuild.
 */
const { withGradleProperties } = require("@expo/config-plugins");

const KEY = "AsyncStorage_db_size_in_MB";
const SIZE_MB = "256";

module.exports = (config) =>
  withGradleProperties(config, (cfg) => {
    const props = cfg.modResults.filter((p) => !(p.type === "property" && p.key === KEY));
    props.push({ type: "property", key: KEY, value: SIZE_MB });
    cfg.modResults = props;
    return cfg;
  });
